name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -project TomatoBar.xcodeproj -scheme TomatoBar

      - name: Build
        run: xcodebuild build -project TomatoBar.xcodeproj -scheme TomatoBar -configuration Debug -destination 'platform=macOS' CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Test
        run: xcodebuild test -project TomatoBar.xcodeproj -scheme TomatoBar -destination 'platform=macOS' -only-testing TomatoBarTests CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO MACOSX_DEPLOYMENT_TARGET=14.0
